frontend/app/basic/urls.py
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib.auth.decorators import login_required
from django.views.generic import RedirectView

from city_issues.views import (
    CheckIssues, DetailedIssue, delete_attachment, get_all_issues_data, get_issue_data,
    HomePageView, map_page_view, IssueCreate, UserProfileView, UpdateIssue, CommentIssues,
    post_comment, issue_action, comment_delete, comment_restore, mod_list_panel, mod_edit_issue,
    delete_issue, restore_issue, imgResponse, mod_comment)


urlpatterns = [
    url(r'^$', HomePageView.as_view(), name='home'),
    url(r'^issues/$', CheckIssues.as_view(), name='issues'),
    url(r'^issue-comment/(?P<pk>[0-9]+)/$', CommentIssues.as_view(), name='issue-comment'),
    url(r'^issue/(?P<pk>\d+)/$', DetailedIssue.as_view(), name='issue'),
    url(r'^delete-attachment/$', delete_attachment, name='delete-attachment'),
    url(r'^postcomment/(?P<issue_id>[0-9]+)/$', post_comment, name='post-comment'),
    url(r'^issueaction/(?P<issue_id>[0-9]+)/$', issue_action, name='issue-action'),
    url(r'^modpanel/$', mod_list_panel, name='modpanel'),
    url(r'^modpanel/(?P<pk>\d+)/edit/$', mod_edit_issue, name='mod_edit'),
    url(r'^modpanel/(?P<pk>\d+)/delete/$', delete_issue, name='delete_issue'),
    url(r'^modpanel/(?P<pk>\d+)/restore/$', restore_issue, name='restore_issue'),
    url(r'^modcomment/(?P<pk>\d+)/$', mod_comment, name='modcomment'),
    url(r'^deletecomment/(?P<issue_id>[0-9]+)/(?P<comment_id>[0-9]+)/$', comment_delete, name='comment-delete'),
    url(r'^restorecomment/(?P<issue_id>[0-9]+)/(?P<comment_id>[0-9]+)/$', comment_restore, name='comment-restore'),
    url(r'^internal-comments/(?P<issue_id>[0-9]+)/$', UserProfileView.get_internal_comments, name='internal-comment'),
    url(r'^store/internal-comments/(?P<issue_id>[0-9]+)/$', UserProfileView.store_internal_comments, name='store-internal-comment'),

    url(r'^map/$', map_page_view, name='map'),
    url(r'^map/getissuebyid/(?P<issue_id>[0-9]+)$',
        get_issue_data, name='issue_data'),
    url(r'^map/getissuesall/$', get_all_issues_data, name='all_issues'),
    url(r'^add-issue', login_required(IssueCreate.as_view()), name='create_issue'),
    url(r'^editissue/(?P<pk>[0-9]+)$', UpdateIssue.as_view(), name='edit_issue'),

    # registration and authorization views
    url(r'^accounts/logout/$', auth_views.logout, kwargs={'next_page': 'home'}, name='auth_logout'),
    url(r'^accounts/profile/$', UserProfileView.as_view(), name='user_profile'),
    url(r'^accounts/', include('registration.backends.simple.urls', namespace='accounts', )),
]

if settings.DEBUG is True:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG is False:
    urlpatterns.append(url(r'^media(?P<path>.*)$', imgResponse, name='media'))

frontend/app/apps/city_issues/models/issues.py
"""
Django models
"""
from __future__ import unicode_literals

import os
import time
from datetime import date, datetime, time

from django.conf import settings
from django.db import models
from django.db.models import Q
from django.utils.timezone import make_aware
from django.core.urlresolvers import reverse

ROLE_ADMIN = 1
ROLE_MODERATOR = 2
ROLE_USER = 3


class Attachments(models.Model):
    """
    Attachment table in the database.
    """

    def get_file_path(self, filename):
        # pylint: disable=no-member
        folder = self.issue.title
        # pylint: enable=no-member
        return os.path.join('uploads', folder, filename)

    def delete(self, *args, **kwargs):
        # pylint: disable=no-member
        storage, path = self.image_url.storage, self.image_url.path
        super(Attachments, self).delete(*args, **kwargs)
        directory_path = os.path.abspath(os.path.join(path, os.pardir))

        head, tail = os.path.split(self.image_url.path)
        thumb_name = "thumb-{}".format(tail)
        thumb_storage, thumb_path = self.image_url.storage, os.path.join(directory_path, thumb_name)
        # pylint: enable=no-member

        storage.delete(path)
        thumb_storage.delete(thumb_path)
        if os.path.isdir(directory_path) and not os.listdir(directory_path):
            os.rmdir(directory_path)

    issue = models.ForeignKey('Issues', models.DO_NOTHING,
                              blank=True, null=True)
    image_url = models.ImageField(
        blank=True, null=True, upload_to=get_file_path)

    class Meta:
        app_label = 'city_issues'
        managed = False
        db_table = 'attachments'


class Category(models.Model):
    """
    Category table in the database.
    """
    category = models.TextField(blank=True, null=True)
    favicon = models.TextField(blank=True, null=True)

    def __unicode__(self):
        return u'{0}'.format(self.category)

    class Meta:
        app_label = 'city_issues'
        managed = False
        db_table = 'category'


class Statuses(models.Model):
    """
    Status table in the database.
    """
    status = models.TextField(blank=True, null=True)

    def __unicode__(self):
        return u'{0}'.format(self.status)

    class Meta:
        app_label = 'city_issues'
        managed = False
        db_table = 'statuses'


class IssueHistory(models.Model):
    """
    IssueHistory table in the database.
    """
    STATUS_ID_NEW = Statuses.objects.get(id=1)

    user = models.ForeignKey('User', models.DO_NOTHING,
                             blank=True, null=True)
    issue = models.ForeignKey('Issues', models.DO_NOTHING,
                              blank=True, null=True)
    status = models.ForeignKey('Statuses', models.DO_NOTHING,
                               blank=True, null=True, default=STATUS_ID_NEW)
    transaction_date = models.DateTimeField(blank=True, null=True,
                                            auto_now_add=True)

    class Meta:
        app_label = 'city_issues'
        managed = False
        db_table = 'issue_History'


class Issues(models.Model):
    """
    Issues table in the database.
    """
    title = models.TextField(blank=True, null=True)
    user = models.ForeignKey('User', models.DO_NOTHING,
                             blank=True, null=True)
    category = models.ForeignKey('Category', models.DO_NOTHING)
    location_lat = models.FloatField(blank=True, null=True)
    location_lon = models.FloatField(blank=True, null=True)
    status = models.TextField(blank=True, null=True, default='new')
    description = models.TextField(blank=True, null=True)
    open_date = models.DateTimeField(blank=True, null=True, auto_now_add=True)
    close_date = models.DateTimeField(blank=True, null=True)
    delete_date = models.DateTimeField(blank=True, null=True)

    class Meta:
        app_label = 'city_issues'
        managed = False
        db_table = 'issues'

    def get_attachments(self):
        return Attachments.objects.filter(issue=self.id)

    def get_role_based_query(self, request):
        """Return issues based on role and author."""
        if request.user.is_anonymous():
            query = Issues.objects.filter(status__in=["open", "closed"])
        if request.user.is_authenticated() and request.user.role.id not in (ROLE_ADMIN, ROLE_MODERATOR):
            query = Issues.objects.filter(
                Q(status__in=["open", "closed"]) | Q(user=request.user.id)).exclude(status="deleted")
        if request.user.is_authenticated() and request.user.role.id in (ROLE_ADMIN, ROLE_MODERATOR):
            query = Issues.objects.all()
        return query

    def issue_filter(self, form, role_based_query):
        """Filter issue by form data."""
        kwargs = {}
        map_date_from = form.cleaned_data.get('date_from')
        map_date_to = form.cleaned_data.get('date_to')
        status_arr = form.data.get('status_arr').split(",")
        category = form.data.get('category')
        search = form.cleaned_data.get('search')

        if status_arr:
            kwargs["status__in"] = status_arr

        date_from = make_aware(datetime(1970, 1, 1,))
        date_to = make_aware(datetime.now())

        if map_date_from:
            date_from = make_aware(
                datetime.combine(map_date_from, time.min))
        if map_date_to:
            date_to = make_aware(datetime.combine(map_date_to, time.max))

        kwargs["open_date__range"] = (date_from, date_to)

        if category:
            kwargs['category'] = category

        query = role_based_query.filter(**kwargs)

        if search:
            query = role_based_query.filter(**kwargs).filter(
                Q(title__icontains=search) | Q(description__icontains=search))
        return query

    def get_issue_data_by_id(self, request, issue_id):
        """Get single issue data."""
        dict_of_actions = self.get_actions_list(request, issue_id)

        attachments_query = list(
            Attachments.objects.filter(issue=issue_id).values())

        comments_list = Comments()
        comments_query = comments_list.get_comments(
            issue_id, dict_of_actions['list_of_comments_statuses'])

        images_urls = [item['image_url'] for item in attachments_query]
        checked_img_urls = []

        for img in images_urls:
            if img and os.path.isfile(os.path.join(settings.MEDIA_ROOT, img)):
                imgurl = img.split('/')
                imgurl[-1] = 'thumb-' + imgurl[-1]
                img = settings.MEDIA_URL + ('/').join(imgurl)
                checked_img_urls.append(img)

        issue_obj = Issues.objects.filter(
            pk=issue_id).select_related("category")
        unpacked_issue_obj = issue_obj[0]

        issue_query = list(issue_obj.values(
            "title",
            "user",
            "category",
            "location_lat",
            "location_lon",
            "status",
            "description",
            "open_date",
            "close_date",
            "delete_date",
            "category__category",))

        issue_dict = issue_query[0]
        issue_dict['images_urls'] = checked_img_urls
        issue_dict['dict_of_actions'] = dict_of_actions
        issue_dict['comments'] = comments_query

        issue_dict['open_date'] = convert_date(issue_dict['open_date'])
        issue_dict['close_date'] = convert_date(issue_dict['close_date'])
        issue_dict['delete_date'] = convert_date(
            issue_dict['delete_date'])

        return issue_query

    def get_actions_list(self, request, issue_id):
        """Return list of allowed actions with issue."""
        list_of_comments_statuses = ['public']
        list_of_actions = []

        if request.user.is_authenticated():

            issue = Issues.objects.get(pk=issue_id)

            user_is_admin_or_moderator = request.user.role.id in (
                ROLE_ADMIN, ROLE_MODERATOR)

            user_is_issue_owner = (issue.user_id == request.user.id)

            if user_is_admin_or_moderator:
                list_of_actions.append('edit')
                list_of_comments_statuses.append('private')
                list_of_comments_statuses.append('internal')

                if issue.status in ('new', 'on moderation'):
                    list_of_actions.append("open")

                if issue.status in ('open', 'pending close'):
                    list_of_actions.append("closed")

                if issue.status != 'deleted':
                    list_of_actions.append("deleted")
            else:
                if user_is_issue_owner:
                    list_of_comments_statuses.append('private')

                    if issue.status in ('new', 'on moderation'):
                        list_of_actions.append("edit")
                    if issue.status == 'open':
                        list_of_actions.append("pending close")

        dict_of_actions = {
            'list_of_comments_statuses': list_of_comments_statuses,
            'list_of_actions': list_of_actions
        }

        return dict_of_actions

    def get_absolute_url(self):
        return reverse("mod_edit", kwargs={"pk": self.pk})

    def mod_delete(self):
        """Setting deleting date for issue"""
        if not self.delete_date:
            self.delete_date = datetime.now()
            return True
        return False

    def mod_restore(self):
        """Restoring issue from deletion"""
        if self.delete_date:
            self.delete_date = None
            return True
        return False


class Comments(models.Model):
    """
    Issues table in the database.
    """
    user = models.ForeignKey('User', models.DO_NOTHING,

frontend/app/apps/city_issues/models/users.py
"""
Django models
"""
from __future__ import unicode_literals

import datetime

from django.contrib.auth.models import AbstractBaseUser
from django.contrib.auth.hashers import make_password
from django.db import models
from passlib.handlers.django import django_bcrypt

from city_issues.user_managers import UserManager


class Role(models.Model):
    """
    Roles table in the database
    """
    role = models.TextField()
    app_label = 'city_issues'

    class Meta:
        managed = False
        db_table = 'roles'


ROLE_ADMIN = Role.objects.get(id=1)
ROLE_MODERATOR = Role.objects.get(id=2)
ROLE_USER = Role.objects.get(id=3)


class User(AbstractBaseUser):
    """
    Users table in the database
    """
    name = models.TextField(
        max_length=50,
        blank=True,
        null=True)
    alias = models.TextField(
        max_length=25,
        unique=True)
    email = models.EmailField(
        max_length=50,
        unique=True)
    hashed_password = models.TextField(
        max_length=256,
        blank=True,
        null=True)
    role = models.ForeignKey(
        'Role',
        default=ROLE_USER)
    avatar = models.ImageField(
        blank=True,
        null=True)
    delete_date = models.DateTimeField(
        blank=True,
        null=True)
    last_login = models.DateTimeField(
        blank=True,
        null=True)

    # Connects a custom user manager
    objects = UserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['alias', 'name']

    def get_full_name(self):
        return self.name

    def get_short_name(self):
        return self.name

    @property
    def password(self):
        return self.hashed_password

    @password.setter
    def password(self, raw_password):
        self.set_password(raw_password)

    def set_password(self, raw_password):
        self.hashed_password = make_password(raw_password)
        self._password = raw_password

    def check_password(self, raw_password):
        """Checking the password form database."""
        return django_bcrypt.verify(raw_password, self.hashed_password)

    @property
    def is_active(self):
        return not self.delete_date

    @is_active.setter
    def is_active(self, value):
        self.delete_date = None if value else datetime.datetime.now()

    @property
    def is_staff(self):
        return self.role == ROLE_MODERATOR

    @is_staff.setter
    def is_staff(self, value):
        if value:
            self.role = ROLE_MODERATOR
        else:
            self.role = ROLE_USER

    @property
    def is_superuser(self):
        return self.role == ROLE_ADMIN

    @is_superuser.setter
    def is_superuser(self, value):
        if value:
            self.role = ROLE_ADMIN
        else:
            self.role = ROLE_USER

    class Meta:
        managed = False
        db_table = 'users'

frontend/app/apps/city_issues/templates/base.html
{% load i18n %}
{% load static from staticfiles %}

<!DOCTYPE html>
<html>
<head>

    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>City Issues -
        {% block meta_title %}{% endblock meta_title %}</title>
    <link rel="stylesheet"
          href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
          integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u"
          crossorigin="anonymous">
    {% block extra_css %}

    {% endblock extra_css %}

</head>
<body>

<!--start navigation-->
<nav class="navbar navbar-default">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <a class="navbar-brand" href="{% url "home" %}">CITY ISSUES</a>
        </div>
        <div class="collapse navbar-collapse"
             id="bs-example-navbar-collapse-1">
            {% if user.is_authenticated %}
                <div class="navbar-form navbar-left">
                    <a href="{% url 'create_issue' %}" class="btn btn-md btn-info">
                        <span class="glyphicon glyphicon-plus"></span> Add issue
                    </a>
                </div>
                <!--<p class="navbar-text navbar-right">You are logged as <a href="#">{{ user.email }}</a></p>-->
                <!--<a href="#" class="navbar-text navbar-left">{{ user.email }}</a>-->
                <a href="{% url "accounts:auth_logout" %}"
                   class="navbar-text navbar-right">Log out</a>
                <a href="{% url "issues" %}"
                   class="navbar-text navbar-right">All Issues</a>
                 <a href="{% url "map" %}"
                 class="navbar-text navbar-right">Map</a>
                <p class="navbar-text navbar-right">You are logged as <a
                        href="{% url 'user_profile' %}">{{ user.email }}</a></p>
            {% else %}
                <a href="{% url "accounts:auth_login" %}"
                   class="navbar-text navbar-right">Sign in</a>
                <a href="{% url "accounts:registration_register" %}"
                   class="navbar-text navbar-right">Sign up</a>
                <a href="{% url "issues" %}"
                   class="navbar-text navbar-right">All Issues</a>
                <a href="{% url "map" %}"
                   class="navbar-text navbar-right">Map</a>
            {% endif %}
            {% if user.is_staff or user.is_superuser %}
                <div class="navbar-form navbar-left">
                <a href="{% url 'modpanel' %}" type="button" class="btn btn-md btn-info">
                    Moderator panel
                </a>
            {% else %}
            {% endif %}

        </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
</nav>
<!--end navigation-->

{% block content %}
{% endblock content %}

<!--scripts-->
<script src="https://code.jquery.com/jquery-3.1.1.js"
        integrity="sha256-16cdPddA6VdVInumRGo6IbivbERE8p7CQR3HzTBuELA="
        crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"
        integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
        crossorigin="anonymous"></script>
{% block extra_js %}{% endblock extra_js %}

</body>
</html>

frontend/app/apps/city_issues/templates/edit_issue.html
{% extends "base.html" %}
{% block meta_title %}Edit issue page{% endblock meta_title %}

{% block extra_css %}
    {% load static %}
    <link rel="stylesheet" type="text/css"
          href="{% static 'css/issues.css' %}"/>
    <link rel="stylesheet" type="text/css"
          href="{% static 'css/general.css' %}"/>
    <link rel="stylesheet"
          href="https://unpkg.com/leaflet@1.2.0/dist/leaflet.css"
          integrity="sha512-M2wvCLH6DSRazYeZRIm1JnYyh22purTM+FDB5CsyxtQJYeKq83arPe5wgbNmcFXGqiSH2XR8dT/fJISVA1r/zQ=="
          crossorigin=""/>
{% endblock extra_css %}

{% block content %}

    <div class="wrapper">
        <div class="width map-width">
            <div class="row">
                {% if messages %}
                    <ul class="messages">
                        {% for message in messages %}
                            <li{% if message.tags %}
                                class="{{ message.tags }}"{% endif %}>
                                {{ message }}
                                <a href="#" class="del-msg">&times;</a>
                            </li>
                        {% endfor %}
                    </ul>
                {% endif %}
            </div>
        </div>
    </div>

    <div class="container">
        <div class="row">
            <div class="col-sm-6">
                <form action="" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <input id="issue_form-submit" class="btn btn-success" type="submit"
                           value="Update"/>
                </form>
                <br>
                <a href="{% url "map" %}" class="btn btn-danger">Return to
                    map</a>

                 <div class="images">
                    {% for image in issues.get_attachments %}
                        <a class="del-img" data-attach-id="{{ image.id }}"
                           data-toggle="modal" data-target="#deleteModal">&times;</a>
                        <img src="{% get_media_prefix %}{{ image.image_url }}"
                             alt="{{ image.image_url }}" class="imgs">
                    {% endfor %}
                </div>
            </div>
            <div class="col-sm-6">
                <div id="map"></div>
            </div>
        </div>
    </div>

    <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog"
         aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal"
                            aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <form action="{% url 'delete-attachment' %}" method="post">
                    {% csrf_token %}
                    <div class="modal-body">
                        <h3>Are you sure delete this image?</h3>
                        <input type="hidden" value="" name="attachment-id">
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary"
                                data-dismiss="modal">Close
                        </button>
                        <button type="submit" class="btn btn-danger">Delete
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </div>

{% endblock content %}

{% block extra_js %}
    <script src="https://unpkg.com/leaflet@1.2.0/dist/leaflet.js"
            integrity="sha512-lInM/apFSqyy1o6s89K4iQUKg6ppXEgsVxT35HbzUupEVRh2Eu9Wdl4tHj7dZO0s1uvplcYGmt3498TtHq+log=="
            crossorigin="">
    </script>

    {% load static %}
    <script type="text/javascript"
            src="{% static "city_issues/js/edit_on_map.js" %}"></script>
    <script type="text/javascript" src="{% static "js/general.js" %}"></script>

{% endblock extra_js %}

frontend/app/apps/city_issues/templates/home_page.html
{% extends "base.html" %}

{% load i18n %}
{% load static from staticfiles %}

{% block meta_title %}Home page{% endblock meta_title %}

{% block content %}

{% endblock content %}

frontend/app/apps/city_issues/templates/issue_detailed.html
{% extends "base.html" %}

{% load i18n %}
{% load static from staticfiles %}

{% block meta_title %}Detailed Issue{% endblock meta_title %}

{% block extra_css %}
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/issues.css' %}"/>
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.2.0/dist/leaflet.css"
          integrity="sha512-M2wvCLH6DSRazYeZRIm1JnYyh22purTM+FDB5CsyxtQJYeKq83arPe5wgbNmcFXGqiSH2XR8dT/fJISVA1r/zQ=="
          crossorigin=""/>
{% endblock extra_css %}

{% block content %}

<div class="container">
		<div class="card">
			<div class="container-fliud">
				<div class="wrapper row">
					<div class="preview col-md-4">
                         {% for image in object.get_attachments %}
                             {% if image.image_url %}
                                <img src="{% get_media_prefix %}{{ image.image_url }}" alt="{{ image.image_url }}" class="imgs">
                             {% else %}
                                 <img src="{% static "city_issues/img/no-image.png" %}" alt="photo" class="img-thumbnail">
                             {% endif %}
                         {% endfor %}
					</div>
					<div class="details col-md-4">
                        <h6 style="float: right">{{ object.status }}</h6>
						<h3 class="product-title">{{ object.title }}</h3>
                        <h4>Created: {{ object.user }}</h4>
                        <h4>Category: {{ object.category }}</h4>
                        <h5>Open date: {{ object.open_date|date:"d/m/y" }}</h5>
                        <h5>Close date: {{ object.close_date|date:"d/m/y" }}</h5>
                        <h5>Latitude: {{ object.location_lat }}</h5>
                        <h5>Longitude: {{ object.location_lon }}</h5>
                        <h5>Description:</h5>
						<p class="product-description">{{ object.description }}</p>
					</div>
                    <div class="col-sm-4">
			            <div id="map" style="width: 330px; height: 330px;"></div>
                    </div>
				</div>
			</div>
            <div class="row">
        <div class="col-md-6">
            <h3>Comments:</h3>
            <table>
            {% for com in  object.comments_set.all %}
               {%  if user.pk == com.user_id or user.role.id == 1 or user.role.id == 2  and com.status != 'internal'%}
               <tr>
                 <td>
                   <h5>{{ com.user.role.role|title }}: {{ com.user.name }} {{ com.date_public }} {{ com.status }}</h5>
                   <p style="text-indent:20px;">{{ com.comment|linebreaksbr }}</p>
                 </td>
                 <td>
                     {% if com.status != 'deleted' %}
                     <a class="btn btn-danger status" data-toggle="modal" data-target="#deletion" data-elem-id="{{ com.id }}" data-func-name="delete" data-elem-name="comment" data-elem-name="comment" data-issue-id="{{ object.pk }}"><span class="glyphicon glyphicon-remove"></span></a>
                     {% elif com.status == 'deleted' %}
                     <a class="btn btn-success status" data-toggle="modal" data-target="#deletion" data-elem-id="{{ com.id }}" data-func-name="restore" data-elem-name="comment" data-issue-id="{{ object.pk }}"><span class="glyphicon glyphicon-ok"></span></a>
                     {% endif %}
                 </td>
                   {% else %}
                   {% if com.status == 'public' %}
                   <td>
                   <h5>{{ com.user.role.role|title }}: {{ com.user.name }} {{ com.date_public }}</h5>
                   <p style="text-indent:20px;">{{ com.comment|linebreaksbr }}</p>
                 </td>
                       {% endif %}
                   {% if user.is_authenticated %}
                       {% if com.status == 'internal' %}
                           <td>
                   <h5>{{ com.user.role.role|title }}: {{ com.user.name }} {{ com.date_public }} {{ com.status }}</h5>
                   <p style="text-indent:20px;">{{ com.comment|linebreaksbr }}</p>
                 </td>
                           {% endif %}
                       {% endif %}
               {% endif %}
              </tr>
            {% endfor %}
            </table>
        </div>
    </div>
   {% if user.is_authenticated %}
          <div class="row">
         <div class="col-sm-6" style="padding-right: 0">
             <br>
             <form action="{% url 'issue-comment' object.pk %}" method="POST">
                {% csrf_token %}
                      <label for={{ form.comment.id_for_label }}>Comment:</label>
                <textarea type="text" class="form-control"
                          rows="5" name="{{ form.comment.name }}" maxlength="400"
                          id={{ form.comment.id_for_label }}></textarea>
                     <br>
                     <input type="radio" name="status" value="public" checked> public<br>
                     <input type="radio" name="status" value="private"> private<br>
                     <input type="radio" name="status" value="internal"> internal<br>
                     <br/>


                 <input type='submit' class="btn btn-primary" value='Comment' name="Comment"/>
                         <br>
                 <!--<button class="btn btn-primary">Comment</button>-->
             </form>
         </div>
    </div>
		</div>
    {% endif %}
</div>


<div class="modal fade" id="deletion" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title"></h4>
      </div>
      <div class="modal-body"> </div>
      <div class="modal-footer">
        <form id="delete-comment" method="post" action="#">
          {% csrf_token %}
          <button type="submit" class="btn button-confirm"> </button>
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </form>
      </div>
    </div>
  </div>
</div>

{% endblock content %}

{% block extra_js %}
    <script src="https://unpkg.com/leaflet@1.2.0/dist/leaflet.js"
            integrity="sha512-lInM/apFSqyy1o6s89K4iQUKg6ppXEgsVxT35HbzUupEVRh2Eu9Wdl4tHj7dZO0s1uvplcYGmt3498TtHq+log=="
            crossorigin="">
    </script>

    {% load static %}
        <script type="text/javascript" src="{% static "city_issues/js/app.js" %}"></script>
        <script type="text/javascript" src="{% static "city_issues/js/edit_on_map.js" %}"></script>
{% endblock extra_js %}