frontend/app/basic/urls.py
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib.auth.decorators import login_required
from django.views.generic import RedirectView

from city_issues.views import (
    CheckIssues, DetailedIssue, delete_attachment, get_all_issues_data, get_issue_data,
    HomePageView, map_page_view, IssueCreate, UserProfileView, UpdateIssue, CommentIssues,
    post_comment, issue_action, comment_delete, comment_restore, mod_list_panel, mod_edit_issue,
    delete_issue, restore_issue, imgResponse, mod_comment)


urlpatterns = [
    url(r'^$', HomePageView.as_view(), name='home'),
    url(r'^issues/$', CheckIssues.as_view(), name='issues'),
    url(r'^issue-comment/(?P<pk>[0-9]+)/$', CommentIssues.as_view(), name='issue-comment'),
    url(r'^issue/(?P<pk>\d+)/$', DetailedIssue.as_view(), name='issue'),
    url(r'^delete-attachment/$', delete_attachment, name='delete-attachment'),
    url(r'^postcomment/(?P<issue_id>[0-9]+)/$', post_comment, name='post-comment'),
    url(r'^issueaction/(?P<issue_id>[0-9]+)/$', issue_action, name='issue-action'),
    url(r'^modpanel/$', mod_list_panel, name='modpanel'),
    url(r'^modpanel/(?P<pk>\d+)/edit/$', mod_edit_issue, name='mod_edit'),
    url(r'^modpanel/(?P<pk>\d+)/delete/$', delete_issue, name='delete_issue'),
    url(r'^modpanel/(?P<pk>\d+)/restore/$', restore_issue, name='restore_issue'),
    url(r'^modcomment/(?P<pk>\d+)/$', mod_comment, name='modcomment'),
    url(r'^deletecomment/(?P<issue_id>[0-9]+)/(?P<comment_id>[0-9]+)/$', comment_delete, name='comment-delete'),
    url(r'^restorecomment/(?P<issue_id>[0-9]+)/(?P<comment_id>[0-9]+)/$', comment_restore, name='comment-restore'),
    url(r'^internal-comments/(?P<issue_id>[0-9]+)/$', UserProfileView.get_internal_comments, name='internal-comment'),
    url(r'^store/internal-comments/(?P<issue_id>[0-9]+)/$', UserProfileView.store_internal_comments, name='store-internal-comment'),

    url(r'^map/$', map_page_view, name='map'),
    url(r'^map/getissuebyid/(?P<issue_id>[0-9]+)$',
        get_issue_data, name='issue_data'),
    url(r'^map/getissuesall/$', get_all_issues_data, name='all_issues'),
    url(r'^add-issue', login_required(IssueCreate.as_view()), name='create_issue'),
    url(r'^editissue/(?P<pk>[0-9]+)$', UpdateIssue.as_view(), name='edit_issue'),

    # registration and authorization views
    url(r'^accounts/logout/$', auth_views.logout, kwargs={'next_page': 'home'}, name='auth_logout'),
    url(r'^accounts/profile/$', UserProfileView.as_view(), name='user_profile'),
    url(r'^accounts/', include('registration.backends.simple.urls', namespace='accounts', )),
]

if settings.DEBUG is True:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG is False:
    urlpatterns.append(url(r'^media(?P<path>.*)$', imgResponse, name='media'))

frontend/app/apps/city_issues/models/issues.py
"""
Django models
"""
from __future__ import unicode_literals

import os
import time
from datetime import date, datetime, time

from django.conf import settings
from django.db import models
from django.db.models import Q
from django.utils.timezone import make_aware
from django.core.urlresolvers import reverse

ROLE_ADMIN = 1
ROLE_MODERATOR = 2
ROLE_USER = 3


class Attachments(models.Model):
    """
    Attachment table in the database.
    """

    def get_file_path(self, filename):
        # pylint: disable=no-member
        folder = self.issue.title
        # pylint: enable=no-member
        return os.path.join('uploads', folder, filename)

    def delete(self, *args, **kwargs):
        # pylint: disable=no-member
        storage, path = self.image_url.storage, self.image_url.path
        super(Attachments, self).delete(*args, **kwargs)
        directory_path = os.path.abspath(os.path.join(path, os.pardir))

        head, tail = os.path.split(self.image_url.path)
        thumb_name = "thumb-{}".format(tail)
        thumb_storage, thumb_path = self.image_url.storage, os.path.join(directory_path, thumb_name)
        # pylint: enable=no-member

        storage.delete(path)
        thumb_storage.delete(thumb_path)
        if os.path.isdir(directory_path) and not os.listdir(directory_path):
            os.rmdir(directory_path)

    issue = models.ForeignKey('Issues', models.DO_NOTHING,
                              blank=True, null=True)
    image_url = models.ImageField(
        blank=True, null=True, upload_to=get_file_path)

    class Meta:
        app_label = 'city_issues'
        managed = False
        db_table = 'attachments'


class Category(models.Model):
    """
    Category table in the database.
    """
    category = models.TextField(blank=True, null=True)
    favicon = models.TextField(blank=True, null=True)

    def __unicode__(self):
        return u'{0}'.format(self.category)

    class Meta:
        app_label = 'city_issues'
        managed = False
        db_table = 'category'


class Statuses(models.Model):
    """
    Status table in the database.
    """
    status = models.TextField(blank=True, null=True)

    def __unicode__(self):
        return u'{0}'.format(self.status)

    class Meta:
        app_label = 'city_issues'
        managed = False
        db_table = 'statuses'


class IssueHistory(models.Model):
    """
    IssueHistory table in the database.
    """
    STATUS_ID_NEW = Statuses.objects.get(id=1)

    user = models.ForeignKey('User', models.DO_NOTHING,
                             blank=True, null=True)
    issue = models.ForeignKey('Issues', models.DO_NOTHING,
                              blank=True, null=True)
    status = models.ForeignKey('Statuses', models.DO_NOTHING,
                               blank=True, null=True, default=STATUS_ID_NEW)
    transaction_date = models.DateTimeField(blank=True, null=True,
                                            auto_now_add=True)

    class Meta:
        app_label = 'city_issues'
        managed = False
        db_table = 'issue_History'


class Issues(models.Model):
    """
    Issues table in the database.
    """
    title = models.TextField(blank=True, null=True)
    user = models.ForeignKey('User', models.DO_NOTHING,
                             blank=True, null=True)
    category = models.ForeignKey('Category', models.DO_NOTHING)
    location_lat = models.FloatField(blank=True, null=True)
    location_lon = models.FloatField(blank=True, null=True)
    status = models.TextField(blank=True, null=True, default='new')
    description = models.TextField(blank=True, null=True)
    open_date = models.DateTimeField(blank=True, null=True, auto_now_add=True)
    close_date = models.DateTimeField(blank=True, null=True)
    delete_date = models.DateTimeField(blank=True, null=True)

    class Meta:
        app_label = 'city_issues'
        managed = False
        db_table = 'issues'

    def get_attachments(self):
        return Attachments.objects.filter(issue=self.id)

    def get_role_based_query(self, request):
        """Return issues based on role and author."""
        if request.user.is_anonymous():
            query = Issues.objects.filter(status__in=["open", "closed"])
        if request.user.is_authenticated() and request.user.role.id not in (ROLE_ADMIN, ROLE_MODERATOR):
            query = Issues.objects.filter(
                Q(status__in=["open", "closed"]) | Q(user=request.user.id)).exclude(status="deleted")
        if request.user.is_authenticated() and request.user.role.id in (ROLE_ADMIN, ROLE_MODERATOR):
            query = Issues.objects.all()
        return query

    def issue_filter(self, form, role_based_query):
        """Filter issue by form data."""
        kwargs = {}
        map_date_from = form.cleaned_data.get('date_from')
        map_date_to = form.cleaned_data.get('date_to')
        status_arr = form.data.get('status_arr').split(",")
        category = form.data.get('category')
        search = form.cleaned_data.get('search')

        if status_arr:
            kwargs["status__in"] = status_arr

        date_from = make_aware(datetime(1970, 1, 1,))
        date_to = make_aware(datetime.now())

        if map_date_from:
            date_from = make_aware(
                datetime.combine(map_date_from, time.min))
        if map_date_to:
            date_to = make_aware(datetime.combine(map_date_to, time.max))

        kwargs["open_date__range"] = (date_from, date_to)

        if category:
            kwargs['category'] = category

        query = role_based_query.filter(**kwargs)

        if search:
            query = role_based_query.filter(**kwargs).filter(
                Q(title__icontains=search) | Q(description__icontains=search))
        return query

    def get_issue_data_by_id(self, request, issue_id):
        """Get single issue data."""
        dict_of_actions = self.get_actions_list(request, issue_id)

        attachments_query = list(
            Attachments.objects.filter(issue=issue_id).values())

        comments_list = Comments()
        comments_query = comments_list.get_comments(
            issue_id, dict_of_actions['list_of_comments_statuses'])

        images_urls = [item['image_url'] for item in attachments_query]
        checked_img_urls = []

        for img in images_urls:
            if img and os.path.isfile(os.path.join(settings.MEDIA_ROOT, img)):
                imgurl = img.split('/')
                imgurl[-1] = 'thumb-' + imgurl[-1]
                img = settings.MEDIA_URL + ('/').join(imgurl)
                checked_img_urls.append(img)

        issue_obj = Issues.objects.filter(
            pk=issue_id).select_related("category")
        unpacked_issue_obj = issue_obj[0]

        issue_query = list(issue_obj.values(
            "title",
            "user",
            "category",
            "location_lat",
            "location_lon",
            "status",
            "description",
            "open_date",
            "close_date",
            "delete_date",
            "category__category",))

        issue_dict = issue_query[0]
        issue_dict['images_urls'] = checked_img_urls
        issue_dict['dict_of_actions'] = dict_of_actions
        issue_dict['comments'] = comments_query

        issue_dict['open_date'] = convert_date(issue_dict['open_date'])
        issue_dict['close_date'] = convert_date(issue_dict['close_date'])
        issue_dict['delete_date'] = convert_date(
            issue_dict['delete_date'])

        return issue_query

    def get_actions_list(self, request, issue_id):
        """Return list of allowed actions with issue."""
        list_of_comments_statuses = ['public']
        list_of_actions = []

        if request.user.is_authenticated():

            issue = Issues.objects.get(pk=issue_id)

            user_is_admin_or_moderator = request.user.role.id in (
                ROLE_ADMIN, ROLE_MODERATOR)

            user_is_issue_owner = (issue.user_id == request.user.id)

            if user_is_admin_or_moderator:
                list_of_actions.append('edit')
                list_of_comments_statuses.append('private')
                list_of_comments_statuses.append('internal')

                if issue.status in ('new', 'on moderation'):
                    list_of_actions.append("open")

                if issue.status in ('open', 'pending close'):
                    list_of_actions.append("closed")

                if issue.status != 'deleted':
                    list_of_actions.append("deleted")
            else:
                if user_is_issue_owner:
                    list_of_comments_statuses.append('private')

                    if issue.status in ('new', 'on moderation'):
                        list_of_actions.append("edit")
                    if issue.status == 'open':
                        list_of_actions.append("pending close")

        dict_of_actions = {
            'list_of_comments_statuses': list_of_comments_statuses,
            'list_of_actions': list_of_actions
        }

        return dict_of_actions

    def get_absolute_url(self):
        return reverse("mod_edit", kwargs={"pk": self.pk})

    def mod_delete(self):
        """Setting deleting date for issue"""
        if not self.delete_date:
            self.delete_date = datetime.now()
            return True
        return False

    def mod_restore(self):
        """Restoring issue from deletion"""
        if self.delete_date:
            self.delete_date = None
            return True
        return False


class Comments(models.Model):
    """
    Issues table in the database.
    """
    user = models.ForeignKey('User', models.DO_NOTHING,

frontend/app/apps/city_issues/models/users.py
"""
Django models
"""
from __future__ import unicode_literals

import datetime

from django.contrib.auth.models import AbstractBaseUser
from django.contrib.auth.hashers import make_password
from django.db import models
from passlib.handlers.django import django_bcrypt

from city_issues.user_managers import UserManager


class Role(models.Model):
    """
    Roles table in the database
    """
    role = models.TextField()
    app_label = 'city_issues'

    class Meta:
        managed = False
        db_table = 'roles'


ROLE_ADMIN = Role.objects.get(id=1)
ROLE_MODERATOR = Role.objects.get(id=2)
ROLE_USER = Role.objects.get(id=3)


class User(AbstractBaseUser):
    """
    Users table in the database
    """
    name = models.TextField(
        max_length=50,
        blank=True,
        null=True)
    alias = models.TextField(
        max_length=25,
        unique=True)
    email = models.EmailField(
        max_length=50,
        unique=True)
    hashed_password = models.TextField(
        max_length=256,
        blank=True,
        null=True)
    role = models.ForeignKey(
        'Role',
        default=ROLE_USER)
    avatar = models.ImageField(
        blank=True,
        null=True)
    delete_date = models.DateTimeField(
        blank=True,
        null=True)
    last_login = models.DateTimeField(
        blank=True,
        null=True)

    # Connects a custom user manager
    objects = UserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['alias', 'name']

    def get_full_name(self):
        return self.name

    def get_short_name(self):
        return self.name

    @property
    def password(self):
        return self.hashed_password

    @password.setter
    def password(self, raw_password):
        self.set_password(raw_password)

    def set_password(self, raw_password):
        self.hashed_password = make_password(raw_password)
        self._password = raw_password

    def check_password(self, raw_password):
        """Checking the password form database."""
        return django_bcrypt.verify(raw_password, self.hashed_password)

    @property
    def is_active(self):
        return not self.delete_date

    @is_active.setter
    def is_active(self, value):
        self.delete_date = None if value else datetime.datetime.now()

    @property
    def is_staff(self):
        return self.role == ROLE_MODERATOR

    @is_staff.setter
    def is_staff(self, value):
        if value:
            self.role = ROLE_MODERATOR
        else:
            self.role = ROLE_USER

    @property
    def is_superuser(self):
        return self.role == ROLE_ADMIN

    @is_superuser.setter
    def is_superuser(self, value):
        if value:
            self.role = ROLE_ADMIN
        else:
            self.role = ROLE_USER

    class Meta:
        managed = False
        db_table = 'users'

frontend/app/apps/city_issues/templates/issues/issues.html
{% extends "home_page.html" %}

{% load i18n %}

{% block meta_title %}Issues page{% endblock meta_title %}

{% block extra_css %}
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/issues.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'css/general.css' %}"/>
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.2.0/dist/leaflet.css"
          integrity="sha512-M2wvCLH6DSRazYeZRIm1JnYyh22purTM+FDB5CsyxtQJYeKq83arPe5wgbNmcFXGqiSH2XR8dT/fJISVA1r/zQ=="
          crossorigin=""/>
{% endblock extra_css %}


{% block content %}
    <div class="wrapper">
        <div class="width">
            <h1>Add new issue</h1>
        </div>

        <div class="width">
            <div class="row">
                {% if messages %}
                    <ul class="messages">
                        {% for message in messages %}
                            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>
                                {{ message }}
                                <a href="#" class="del-msg">&times;</a>
                            </li>
                        {% endfor %}
                    </ul>
                {% endif %}
            </div>
            <div class="row">
                <div class="col-md-8">
                    <div id="map"></div>
                </div>
                <div class="col-md-4">
                    <form action="{% url 'create_issue' %}" method="post" enctype="multipart/form-data" id="issue_create-form">
                        {% csrf_token %}
                        <div class="row">
                            <div class="col-md-12">
                                <p>Click on map and add issue marker</p>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group required">
                                    <label for="id_location_lon" class="control-label">Latitude </label>
                                    {{ form.location_lat }}
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group required">
                                    <label for="id_location_lon" class="control-label">Longitude </label>
                                    {{ form.location_lon }}
                                </div>
                            </div>
                        </div>
                        <div class="form-group required">
                            <label for="issue-description" class="control-label">Issue title </label>
                            {{ form.title }}
                        </div>
                        <div class="form-group required">
                            <label for="issue-description" class="control-label">Short description </label>
                            {{ form.description }}
                        </div>
                        <div class="form-group required">
                            <label for="issue-category" class="control-label">Select a category </label>
                            {{ form.category }}
                        </div>

                        <div class="file-upload form-group" data-text="Select image">
                            <label for="">Select image</label>
                            {{ form.files }}
                        </div>

                        <button type="submit" class="btn btn-primary" id="form_submit-btn">Submit</button>
                    </form>

                </div>
            </div>
        </div>
    </div>
{% endblock content %}


{% block extra_js %}
    <script src="https://unpkg.com/leaflet@1.2.0/dist/leaflet.js"
            integrity="sha512-lInM/apFSqyy1o6s89K4iQUKg6ppXEgsVxT35HbzUupEVRh2Eu9Wdl4tHj7dZO0s1uvplcYGmt3498TtHq+log=="
            crossorigin="">
    </script>

    {% load static %}
    <script type="text/javascript" src="{% static "js/issues.js" %}"></script>
    <script type="text/javascript" src="{% static "js/general.js" %}"></script>

{% endblock extra_js %}